source("setup.R")

if (Sys.getenv("NOT_CRAN") != "true") exit_file("Skipping database tests on CRAN")
if (!postgresHasDefault()) exit_file("No default PostgreSQL connection")

try_silent <- function(expr) try(expr, silent = TRUE)

# autocommit
con <- postgresDefault()
con2 <- postgresDefault()
dbCreateTable(con, "a", data.frame(a = 1))
expect_equal(sort(dbListTables(con2)), "a")
try_silent(dbRemoveTable(con, "a"))
dbDisconnect(con)
dbDisconnect(con2)

# commit unnamed transactions
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbCreateTable(con, "a", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), character())
dbCommit(con)
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), "a")
dbCreateTable(con, "b", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), c("a", "b"))
expect_equal(sort(dbListTables(con2)), c("a", "b"))
try_silent(dbRemoveTable(con, "a"))
try_silent(dbRemoveTable(con, "b"))
dbDisconnect(con)
dbDisconnect(con2)

# rollback unnamed transactions
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbCreateTable(con, "a", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), character())
dbRollback(con)
expect_equal(sort(dbListTables(con)), character())
expect_equal(sort(dbListTables(con2)), character())
dbCreateTable(con, "b", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "b")
expect_equal(sort(dbListTables(con2)), "b")
try_silent(dbRemoveTable(con, "b"))
dbDisconnect(con)
dbDisconnect(con2)

# no nested unnamed transactions (commit after error)
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
expect_error(dbBegin(con))
dbCommit(con)
dbCreateTable(con, "a", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), "a")
try_silent(dbRemoveTable(con, "a"))
dbDisconnect(con)
dbDisconnect(con2)

# named transactions need unnamed transaction
con <- postgresDefault()
expect_error(dbBegin(con, name = "tx"))
dbDisconnect(con)

# commit named transactions
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbBegin(con, name = "tx")
dbCreateTable(con, "a", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), character())
dbCommit(con, name = "tx")
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), character())
dbCommit(con)
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), "a")
dbCreateTable(con, "b", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), c("a", "b"))
expect_equal(sort(dbListTables(con2)), c("a", "b"))
try_silent(dbRemoveTable(con, "a"))
try_silent(dbRemoveTable(con, "b"))
dbDisconnect(con)
dbDisconnect(con2)

# rollback named transactions
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbBegin(con, name = "tx")
dbCreateTable(con, "a", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), character())
dbRollback(con, name = "tx")
expect_equal(sort(dbListTables(con)), character())
expect_equal(sort(dbListTables(con2)), character())
dbRollback(con)
expect_equal(sort(dbListTables(con)), character())
expect_equal(sort(dbListTables(con2)), character())
dbCreateTable(con, "b", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "b")
expect_equal(sort(dbListTables(con2)), "b")
try_silent(dbRemoveTable(con, "b"))
dbDisconnect(con)
dbDisconnect(con2)

# nested named transactions (commit - commit)
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbBegin(con, name = "tx")
dbCreateTable(con, "a", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), character())
dbBegin(con, name = "tx2")
dbCreateTable(con, "b", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), c("a", "b"))
expect_equal(sort(dbListTables(con2)), character())
dbCommit(con, name = "tx2")
expect_equal(sort(dbListTables(con)), c("a", "b"))
expect_equal(sort(dbListTables(con2)), character())
dbCommit(con, name = "tx")
expect_equal(sort(dbListTables(con)), c("a", "b"))
expect_equal(sort(dbListTables(con2)), character())
dbCommit(con)
expect_equal(sort(dbListTables(con)), c("a", "b"))
expect_equal(sort(dbListTables(con2)), c("a", "b"))
dbCreateTable(con, "c", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), c("a", "b", "c"))
expect_equal(sort(dbListTables(con2)), c("a", "b", "c"))
try_silent(dbRemoveTable(con, "a"))
try_silent(dbRemoveTable(con, "b"))
try_silent(dbRemoveTable(con, "c"))
dbDisconnect(con)
dbDisconnect(con2)

# nested named transactions (commit - rollback)
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbBegin(con, name = "tx")
dbCreateTable(con, "a", data.frame(a = 1))
dbBegin(con, name = "tx2")
dbCreateTable(con, "b", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), c("a", "b"))
dbCommit(con, name = "tx2")
dbRollback(con, name = "tx")
expect_equal(sort(dbListTables(con)), character())
dbRollback(con)
dbCreateTable(con, "c", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "c")
expect_equal(sort(dbListTables(con2)), "c")
try_silent(dbRemoveTable(con, "c"))
dbDisconnect(con)
dbDisconnect(con2)

# nested named transactions (rollback - commit)
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbBegin(con, name = "tx")
dbCreateTable(con, "a", data.frame(a = 1))
dbBegin(con, name = "tx2")
dbCreateTable(con, "b", data.frame(a = 1))
dbRollback(con, name = "tx2")
expect_equal(sort(dbListTables(con)), "a")
dbCommit(con, name = "tx")
dbCommit(con)
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), "a")
dbCreateTable(con, "c", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), c("a", "c"))
try_silent(dbRemoveTable(con, "a"))
try_silent(dbRemoveTable(con, "c"))
dbDisconnect(con)
dbDisconnect(con2)

# nested named transactions (rollback - rollback)
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbBegin(con, name = "tx")
dbCreateTable(con, "a", data.frame(a = 1))
dbBegin(con, name = "tx2")
dbCreateTable(con, "b", data.frame(a = 1))
dbRollback(con, name = "tx2")
expect_equal(sort(dbListTables(con)), "a")
dbRollback(con, name = "tx")
expect_equal(sort(dbListTables(con)), character())
dbRollback(con)
dbCreateTable(con, "c", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "c")
expect_equal(sort(dbListTables(con2)), "c")
try_silent(dbRemoveTable(con, "c"))
dbDisconnect(con)
dbDisconnect(con2)

# named transactions with keywords
con <- postgresDefault()
con2 <- postgresDefault()
dbBegin(con)
dbBegin(con, name = "SELECT")
dbCreateTable(con, "a", data.frame(a = 1))
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), character())
dbCommit(con, name = "SELECT")
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), character())
dbCommit(con)
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), "a")
dbBegin(con)
dbBegin(con, name = "WHERE")
dbCreateTable(con, "b", data.frame(b = 1))
expect_equal(sort(dbListTables(con)), c("a", "b"))
expect_equal(sort(dbListTables(con2)), "a")
dbRollback(con, name = "WHERE")
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), "a")
dbRollback(con)
expect_equal(sort(dbListTables(con)), "a")
expect_equal(sort(dbListTables(con2)), "a")
try_silent(dbRemoveTable(con, "a"))
try_silent(dbRemoveTable(con, "b"))
dbDisconnect(con)
dbDisconnect(con2)
